version: '3'
services:
  pythonside:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    networks:
      - default
  nginxside:
    build:
      context: .
      dockerfile: ./Dockerfile1
    ports:
      - 80:80
    networks:
      - default
volumes:
  data: